### ISSUE TITLE
Example in user doc to Hyper-parameter search intent and intent pipeline does not work

### ISSUE THREAD

**Issue by jichaogp** [georgianpartners/foreshadow#47]
#### Description

When trying to use the example in user doc to search all feasible intent for a column by adding a combinations section in the json configuration for x preprocessor as  
```json
    "combinations": [
        {
            "columns.age.intent": "['NumericIntent', 'CategoricalIntent']"
        }
    ]
```
I found that the actual pipeline did not change for the column. When trying to tune the actual transformer in the pipeline for a column as 
```json
"columns.fnlwgt.pipeline.2.transformer": "['StandardScaler', 'MinMaxScaler']",
```
 it failed with an exception:
```exception
Traceback (most recent call last):
  File "/Users/jichao/PycharmProjects/foreshadow_demo/examples/adult_2.py", line 27, in <module>
    model.fit(X_train, y_train)
  File "/Users/jichao/PycharmProjects/foreshadow_demo/foreshadow/foreshadow.py", line 180, in fit
    param_ranges = _param_mapping(deepcopy(self.pipeline), X_df, y_df)
  File "/Users/jichao/PycharmProjects/foreshadow_demo/foreshadow/optimizers/param_mapping.py", line 60, in _param_mapping
    pipeline.set_params(**{"{}__from_json".format(k): v for k, v in task.items()})
  File "/Users/jichao/PycharmProjects/foreshadow/venv/lib/python3.6/site-packages/sklearn/pipeline.py", line 142, in set_params
    self._set_params('steps', **kwargs)
  File "/Users/jichao/PycharmProjects/foreshadow/venv/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 49, in _set_params
    super(_BaseComposition, self).set_params(**params)
  File "/Users/jichao/PycharmProjects/foreshadow/venv/lib/python3.6/site-packages/sklearn/base.py", line 282, in set_params
    valid_params[key].set_params(**sub_params)
  File "/Users/jichao/PycharmProjects/foreshadow_demo/foreshadow/preprocessor.py", line 327, in set_params
    self._init_json()
  File "/Users/jichao/PycharmProjects/foreshadow_demo/foreshadow/preprocessor.py", line 317, in _init_json
    raise e
  File "/Users/jichao/PycharmProjects/foreshadow_demo/foreshadow/preprocessor.py", line 297, in _init_json
    self._pipeline_map[k] = resolve_pipeline(v["pipeline"])
  File "/Users/jichao/PycharmProjects/foreshadow_demo/foreshadow/preprocessor.py", line 526, in resolve_pipeline
    "Params {} invalid for transfomer {}".format(params, cls.__name__)
ValueError: Params {'y_var': False, 'override': None, 'name': 'scaler', 'keep_columns': False} invalid for transfomer StandardScaler
```
#### Steps/Code to Reproduce

We can use the following code to reproduce the error:
```python
import pandas as pd
from sklearn.metrics import classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
import foreshadow as fs
import json

RANDOM_SEED = 42

adult = pd.read_csv('adult.csv').iloc[:1000]

print(adult.head())
features = adult.drop(columns='class')
target = adult[['class']]
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=RANDOM_SEED)

# Load in the configs from file
x_proc = json.load(open("adult_x_proc_search.json", "r"))
y_proc = json.load(open("adult_y_proc.json", "r"))

# Create the preprocessors
x_processor = fs.Preprocessor(from_json=x_proc)
y_processor = fs.Preprocessor(from_json=y_proc)
model = fs.Foreshadow(X_preprocessor=x_processor, y_preprocessor=y_processor,
                      estimator=LogisticRegression(random_state=RANDOM_SEED), optimizer=GridSearchCV)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Accuracy = %f' % accuracy_score(y_test, y_pred))

# Serialize the pipeline
x_proc = model.X_preprocessor.serialize()
y_proc = model.y_preprocessor.serialize()

# Write the serialized pipelines to file
json.dump(x_proc, open("adult_x_proc_searched.json", "w"), indent=4)
json.dump(y_proc, open("adult_y_proc_searched.json", "w"), indent=4)
```

Here are corresponding adult_x_proc_search.json
```json
{
    "columns": {
        "age": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "NumericIntent",
                "CategoricalIntent"
            ]
        },
        "workclass": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        },
        "fnlwgt": {
            "intent": "NumericIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "SimpleImputer",
                    "name": "simple_imputer",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "simple_imputer",
                        "keep_columns": false
                    }
                },
                {
                    "transformer": "Scaler",
                    "name": "scaler",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "scaler",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "NumericIntent"
            ]
        },
        "education": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        },
        "education-num": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "NumericIntent",
                "CategoricalIntent"
            ]
        },
        "marital-status": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        },
        "occupation": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        },
        "relationship": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        },
        "race": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        },
        "sex": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        },
        "capital-gain": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "NumericIntent",
                "CategoricalIntent"
            ]
        },
        "capital-loss": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "NumericIntent",
                "CategoricalIntent"
            ]
        },
        "hours-per-week": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "NumericIntent",
                "CategoricalIntent"
            ]
        },
        "native-country": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        }
    },
    "postprocess": [],
    "intents": {
        "GenericIntent": {
            "multi": [
                {
                    "transformer": "MultiImputer",
                    "name": "multi_impute",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "multi_impute",
                        "keep_columns": false
                    }
                }
            ],
            "single": []
        },
        "NumericIntent": {
            "multi": [],
            "single": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": null,
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "SimpleImputer",
                    "name": "simple_imputer",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": null,
                        "keep_columns": false
                    }
                },
                {
                    "transformer": "Scaler",
                    "name": "scaler",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": null,
                        "keep_columns": false
                    }
                }
            ]
        },
        "CategoricalIntent": {
            "multi": [],
            "single": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": null,
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": null,
                        "keep_columns": false
                    }
                }
            ]
        }
    },
    "y_var": false,
    "combinations": [
        {
            "columns.age.intent": "['NumericIntent', 'CategoricalIntent']",
            "columns.fnlwgt.pipeline.2.transformer": "['StandardScaler', 'MinMaxScaler']"
        }
    ]
}
```
To reproduce the first issue, we need to remove the second element in the combinations section.
Here is the corresponding adult_y_proc.json
```json
{
    "columns": {
        "class": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": true,
                        "override": null,
                        "name": null,
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "CategoricalIntent"
            ]
        }
    },
    "postprocess": [],
    "intents": {
        "GenericIntent": {
            "multi": [],
            "single": []
        },
        "CategoricalIntent": {
            "multi": [],
            "single": [
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": true,
                        "override": null,
                        "name": null,
                        "keep_columns": false
                    }
                }
            ]
        }
    },
    "y_var": true
}
```

**Comment by jichaogp** [comment]
My investigation shows that the problem comes from how we use the choices from the combinations section to override the corresponding column section in the config.

For example, when we use the NumericIntent from the combinations section to overwrite the config for 'age' column, the intent was changed, but the config for 'age' column also have the config for the pipeline, which takes higher priority when parsing the config to set up the pipeline for the column. The same reason applies to the second issue as well. When we override a transformer in the pipeline for the 'fnlwgt' column, the parameters section for the old transformer stays and Foreshadow is trying to use it as parameters for the overriding transformer's constructor.
